Multiple updates 4
ihebski/DefaultCreds-cheat-sheet pull request #34
Opened 2022-09-11 12:02 UTC by crypt0rr

Added some new ones, sorted everything and removed some duplicates.

* Hitachi https://www.pdf-manuals.com/pdf/hitachi-cp-wx4022wn-4000-lumens-wxga-lcd-projector-cp-wx4022wn-220717-user-manual.pdf
* Marshall Electronics https://www.search-manual.com/pdf/marshall-electronics-vs-102-hdsdi-h-264-based-video-server-110961-user-manual.pdf
* Lorex https://www.search-manual.com/upload/lorex-lhv210800-hdd-8-channel-security-dvr-system-user-manual.pdf
* Marantz https://www.search-manual.com/pdf/marantz-pmd-901v-night-vision-body-camera-with-gps-425088-user-manual.pdf
* Lumens https://www.search-manual.com/pdf/lumens-wireless-base-for-ladibug-document-camera-226539-user-manual.pdf
* EverFocus https://www.search-manual.com/pdf/everfocus-esk-1000-ip-sidekick-camera-utility-tool-159067-user-manual.pdf
* Sony https://www.search-manual.com/pdf/sony-vpl-fhz700l-7000-lumens-wuxga-laser-light-projector-420741-user-manual.pdf
* Hitachi https://www.search-manual.com/pdf/hitachi-alpha-22-class-full-hd-led-tv-320060-user-manual.pdf
* Sylvania https://www.search-manual.com/pdf/sylvania-sdvd9020b-9-portable-dvd-player-158070-user-manual.pdf
* DJI (OSMO) https://www.search-manual.com/pdf/dji-osmo-4k-camera-with-sport-accessory-kit-425548-user-manual.pdf
* EPSON https://www.search-manual.com/pdf/epson-brightlink-536wi-interactive-wxga-3lcd-projector-230370-user-manual.pdf
* Fujitsu Siemens https://www.search-manual.com/pdf/fujitsu-fi-5950-color-duplex-document-scanner-160120-user-manual.pdf

2022-09-11 14:30 UTC, noraj requested changes

2022-09-11 14:30 UTC, noraj commented on DefaultCreds-Cheat-Sheet.csv
> -productvendor,username,password
You moved or removed the headers!

2022-09-12 01:23 UTC, ihebski approved these changes

2022-09-12 01:24 UTC, merged

2022-09-12 01:26 UTC, ihebski commented
Awesome work @crypt0rr , please always keep the header of the dataset of the csv file.
Thanks a lot